package com.evgeshaog.warcraft3soundboardapplication.domain.model

import com.evgeshaog.warcraft3soundboardapplication.R

val allianceSoundPack = listOf(
    SoundboardItemModel(8, R.drawable.arthas, R.raw.arthas_yes_attack1),
    SoundboardItemModel(8, R.drawable.arthas, R.raw.arthas_yes4),
    SoundboardItemModel(4, R.drawable.paladin, R.raw.paladin),
    SoundboardItemModel(4, R.drawable.paladin, R.raw.paladin_2),
    SoundboardItemModel(6, R.drawable.mountain_king, R.raw.muradin_pissed4),
    SoundboardItemModel(6, R.drawable.mountain_king, R.raw.muradin_what4),
    SoundboardItemModel(6, R.drawable.mountain_king, R.raw.mountain_king_what1),
    SoundboardItemModel(6, R.drawable.mountain_king, R.raw.mountain_king_what2),
    SoundboardItemModel(3, R.drawable.peasant, R.raw.peasant_what3),
    SoundboardItemModel(3, R.drawable.peasant, R.raw.peasant_yes1),
    SoundboardItemModel(3, R.drawable.peasant, R.raw.peasant_yes_attack4),
    SoundboardItemModel(3, R.drawable.peasant, R.raw.peasant_yes2),
    SoundboardItemModel(7, R.drawable.rifleman, R.raw.rifleman_pissed1),
    SoundboardItemModel(7, R.drawable.rifleman, R.raw.rifleman_pissed5),
    SoundboardItemModel(7, R.drawable.rifleman, R.raw.rifleman_pissed4),
    SoundboardItemModel(7, R.drawable.rifleman, R.raw.rifleman_pissed8),
    SoundboardItemModel(5, R.drawable.sorceress, R.raw.sorceress_what4),
    SoundboardItemModel(9, R.drawable.priest, R.raw.priest_pissed5),
    SoundboardItemModel(1, R.drawable.gryphon_rider, R.raw.gryphon_rider_what3),
    SoundboardItemModel(2, R.drawable.mortar_team, R.raw.mortar_team_pissed4),
)

val hordeSoundPack = listOf(
    SoundboardItemModel(1, R.drawable.blademaster, R.raw.blademaster_pissed1),
    SoundboardItemModel(6, R.drawable.tauren_chieftain, R.raw.tauren_chieftain),
    SoundboardItemModel(2, R.drawable.grunt, R.raw.grunt_pissed1),
    SoundboardItemModel(2, R.drawable.grunt, R.raw.grunt_pissed3),
    SoundboardItemModel(3, R.drawable.troll_headhunter, R.raw.headhunter_ready1),
    SoundboardItemModel(3, R.drawable.troll_headhunter, R.raw.headhunter_pissed3),
    SoundboardItemModel(3, R.drawable.troll_headhunter, R.raw.headhunter_pissed4),
    SoundboardItemModel(3, R.drawable.troll_headhunter, R.raw.headhunter_pissed5),
    SoundboardItemModel(4, R.drawable.witch_doctor, R.raw.witch_doctor_pissed6),
    SoundboardItemModel(5, R.drawable.peon, R.raw.peon_pissed1),
    SoundboardItemModel(5, R.drawable.peon, R.raw.peon_ready1),
    SoundboardItemModel(5, R.drawable.peon, R.raw.peon_yes4),
    SoundboardItemModel(7, R.drawable.raider, R.raw.wolfrider_pissed2),
    SoundboardItemModel(7, R.drawable.raider, R.raw.wolfrider_ready1),
)

val nightElfSoundPack = listOf(
    SoundboardItemModel(1, R.drawable.demon_hunter, R.raw.demon_hunter_pissed7),
    SoundboardItemModel(1, R.drawable.demon_hunter, R.raw.demon_hunter_what3),
    SoundboardItemModel(1, R.drawable.demon_hunter, R.raw.demon_hunter_yes3),
    SoundboardItemModel(1, R.drawable.demon_hunter, R.raw.demon_hunter_yes5),
    SoundboardItemModel(2, R.drawable.priestess_of_the_moon, R.raw.moon_priestess_pissed5),
    SoundboardItemModel(2, R.drawable.priestess_of_the_moon, R.raw.moon_priestess_yes4),
    SoundboardItemModel(3, R.drawable.archer, R.raw.archer_pissed2),
    SoundboardItemModel(3, R.drawable.archer, R.raw.archer_pissed3),
    SoundboardItemModel(3, R.drawable.archer, R.raw.archer_pissed7),
    SoundboardItemModel(3, R.drawable.archer, R.raw.archer_pissed8),
    SoundboardItemModel(4, R.drawable.druid_of_the_claw, R.raw.druid_of_the_claw_pissed3),
    SoundboardItemModel(4, R.drawable.druid_of_the_claw, R.raw.druid_of_the_claw_pissed6),
    SoundboardItemModel(5, R.drawable.druid_of_the_talon, R.raw.druid_of_the_talon_pissed2),
    SoundboardItemModel(5, R.drawable.druid_of_the_talon, R.raw.druid_of_the_talon_pissed5),
    SoundboardItemModel(6, R.drawable.dryad, R.raw.dryad_pissed6),
    SoundboardItemModel(6, R.drawable.dryad, R.raw.dryad_ready1),
    SoundboardItemModel(6, R.drawable.dryad, R.raw.dryad_what1),
    SoundboardItemModel(6, R.drawable.dryad, R.raw.dryad_yes3),
    SoundboardItemModel(7, R.drawable.huntress, R.raw.huntress_pissed2),
    SoundboardItemModel(7, R.drawable.huntress, R.raw.huntress_pissed5),
    SoundboardItemModel(8, R.drawable.wisp, R.raw.wisp_what3),
    SoundboardItemModel(8, R.drawable.wisp, R.raw.wisp_yes3),
)

val undeadSoundPack = listOf(
    SoundboardItemModel(1, R.drawable.dread_lord, R.raw.dreadlord_die),
    SoundboardItemModel(1, R.drawable.dread_lord, R.raw.dreadlord_pissed1),
    SoundboardItemModel(1, R.drawable.dread_lord, R.raw.dreadlord_pissed2),
    SoundboardItemModel(1, R.drawable.dread_lord, R.raw.dreadlord_pissed4),
    SoundboardItemModel(1, R.drawable.dread_lord, R.raw.dreadlord_yes1),
    SoundboardItemModel(1, R.drawable.dread_lord, R.raw.dreadlord_yes2),
    SoundboardItemModel(2, R.drawable.lich, R.raw.lich_pissed2),
    SoundboardItemModel(2, R.drawable.lich, R.raw.lich_what1),
    SoundboardItemModel(2, R.drawable.lich, R.raw.lich_yes5),
    SoundboardItemModel(2, R.drawable.lich, R.raw.lich_yes_attack1),
    SoundboardItemModel(3, R.drawable.necromancer, R.raw.necromancer_pissed4),
    SoundboardItemModel(3, R.drawable.necromancer, R.raw.necromancer_pissed5),
    SoundboardItemModel(4, R.drawable.acolyte, R.raw.acolyte_pissed7),
    SoundboardItemModel(4, R.drawable.acolyte, R.raw.acolyte_pissed8),
    SoundboardItemModel(4, R.drawable.acolyte, R.raw.acolyte_what1),
    SoundboardItemModel(4, R.drawable.acolyte, R.raw.acolyte_yes2),
    SoundboardItemModel(5, R.drawable.ghoul, R.raw.ghoul_ready1),
    SoundboardItemModel(5, R.drawable.ghoul, R.raw.ghoul_what2),
    SoundboardItemModel(5, R.drawable.ghoul, R.raw.ghoul_what4),
    SoundboardItemModel(6, R.drawable.abomination, R.raw.abomination_pissed4),
    SoundboardItemModel(7, R.drawable.shade, R.raw.shade_pissed5),
    SoundboardItemModel(7, R.drawable.shade, R.raw.shade_pissed6),
)

